"""
Rubric engine + status inference + rationale generation.

Takes the buyer's rubric (passed through as-is, since the buyer is the one
who decides pass/partial/fail) and produces:
  - The inferred decision.status (if the caller didn't supply one)
  - A weighted score summary
  - A composed rationale string (if the caller didn't supply one)

This module is intentionally simple: the heavy lifting of *evaluating* a vendor
against a rubric belongs to the human reviewer. The service's job is to
package those judgments into a schema-valid Decision Card.

Future versions can add automated-evaluator hooks that pre-fill the rubric
results based on patterns in the fetched documents (e.g. "AEO declares
bias_audit_uri? mark MEASURE_2_5 = pass-with-condition until the URI resolves").
"""

from __future__ import annotations

from collections import Counter

from .models import DecisionStatus, RubricCriterion


def infer_status(rubric: list[RubricCriterion]) -> DecisionStatus:
    """
    Given the rubric results, infer a sensible default decision status.

    Rules (most-severe wins):
      - Any `fail`              -> "rejected-with-remediation"
      - Any `partial`           -> "approved-with-conditions"
      - Any `pass-with-condition` -> "approved-with-conditions"
      - All results in {pass, n/a, and at least one pass} -> "approved"
      - Empty rubric or all n/a -> "pending"

    Callers can override by passing `proposed_status` on the request.
    """
    if not rubric:
        return "pending"

    counts: Counter[str] = Counter(c.result for c in rubric)

    if counts["fail"] > 0:
        return "rejected-with-remediation"
    if counts["partial"] > 0 or counts["pass-with-condition"] > 0:
        return "approved-with-conditions"
    if counts["pass"] > 0:
        return "approved"
    # Everything was n/a — there's no real decision yet.
    return "pending"


def weighted_score(rubric: list[RubricCriterion]) -> float | None:
    """
    Compute a 0-1 weighted score over criteria that have weights.

    Mapping:
      pass               -> 1.0
      pass-with-condition -> 0.75
      partial            -> 0.5
      fail               -> 0.0
      n/a                -> excluded from the calculation

    Returns None if no criterion has a weight or all criteria are n/a.
    """
    if not rubric:
        return None

    result_value = {
        "pass": 1.0,
        "pass-with-condition": 0.75,
        "partial": 0.5,
        "fail": 0.0,
        "n/a": None,  # excluded
    }

    total_weight = 0.0
    weighted_sum = 0.0
    for c in rubric:
        v = result_value[c.result]
        if v is None:
            continue
        w = c.weight if c.weight is not None else 1.0
        total_weight += w
        weighted_sum += w * v

    if total_weight == 0:
        return None
    return weighted_sum / total_weight


def compose_rationale(
    rubric: list[RubricCriterion],
    *,
    status: DecisionStatus,
    vendor_name: str,
    product_name: str | None,
    documents_count: int,
) -> str:
    """Build a default rationale paragraph when the buyer doesn't supply one."""
    subject = f"{vendor_name}" + (f" — {product_name}" if product_name else "")
    counts: Counter[str] = Counter(c.result for c in rubric)
    score = weighted_score(rubric)
    score_str = f" (weighted score: {score:.2f})" if score is not None else ""

    parts: list[str] = []
    parts.append(
        f"Procurement review of {subject} across {documents_count} reviewed document(s). "
        f"Outcome: {status.replace('-', ' ')}{score_str}."
    )

    summary_pieces: list[str] = []
    for label in ("pass", "pass-with-condition", "partial", "fail", "n/a"):
        if counts[label]:
            summary_pieces.append(f"{counts[label]} {label}")
    if summary_pieces:
        parts.append("Rubric results: " + ", ".join(summary_pieces) + ".")

    fails = [c for c in rubric if c.result == "fail"]
    if fails:
        parts.append(
            "Failing criteria: "
            + "; ".join(f"`{c.id}`{' — ' + c.notes if c.notes else ''}" for c in fails)
            + "."
        )

    partials = [c for c in rubric if c.result in ("partial", "pass-with-condition")]
    if partials and status == "approved-with-conditions":
        parts.append("Conditions stem from: " + "; ".join(f"`{c.id}`" for c in partials) + ".")

    parts.append(
        "This rationale was generated by procurement-decision-api. "
        "Review and revise before publishing the Decision Card."
    )

    return " ".join(parts)
